#!/usr/bin/env bash
set -o errexit
set -o xtrace
set -o nounset
set -o pipefail

# Usage: ./tcp_connect <Connection Protocol> <Country Abbreviation>
#   <Connection Protocol>: tcp or udp
#   <Country Abbreviation>: Abbreviation for the country you want to vpn in to
CONNECTION_PROTOCOL="${1}"
COUNTRY="${2}"

# Set location for possible servers
SERVER_BASE="/etc/openvpn/ovpn_${CONNECTION_PROTOCOL}/"

# Read in servers with the abbreviation <country abbreviation>
SERVER_ARRAY=($(ls "${SERVER_BASE}" | grep "${COUNTRY}"))

# Function to compute average speed
test_speed () {
  # Set paramaters for selecting a selecting the fastest server
  SERVER="${1}" # Name of server to test
  NUM_TESTS="${2}"  # Number of speed tests to average for each server
  AVG_SPEED=0 # Variable for storing the average speed of each server


  # Launch a vpn connection in the background
  openvpn "${SERVER}" &

  # Perform the selected number of speed tests and add the results
  for (( i=0; i<"${NUM_TESTS}"; i++)); do
    SPEED=$( speedtest-cli | awk '{if ($1 == "Download:") print substr($2, 1, length($2)-3)}' )
    AVG_SPEED=$(("${AVG_SPEED}" + "${SPEED}"))
  done

  # Close the vpn connection
  killall openvpn

  # Compute the average of the speed test results
  AVG_SPEED=$(( "${AVG_SPEED}" / 3 ))
}

# Function to get a random server
random_server () {
  SERVER_ARRAY="${1}"

  # Generate a random number
  RANDOM_NUM="$(od -vAn -N3 -tu4 < /dev/urandom)"
  
  # Get the total number of servers in the selected country
  TOTAL_SERVERS="${#SERVER_ARRAY[@]}"
  
  # Use modulo arithmatic to get a random number within the number of servers
  RANDOM_SERVER_NUM=$(("${RANDOM_NUM}"%"${TOTAL_SERVERS}"))
  
  # Get the name of the server associated with the random number
  RANDOM_SERVER="${SERVER_BASE}${SERVER_ARRAY[${RANDOM_SERVER_NUM}]}"

  # Return Random Server
  echo "${RANDOM_SERVER}"
}

# Set paramaters for selecting a selecting the fastest server
NUM_SERVERS=1 # Number of servers to speed test before selecting the fastest
NUM_TESTS=1  # Number of speed tests to average for each server
MAX_SPEED=1  # Number of speed tests to average for each server
TOTAL_SERVERS=1 # Total number of servers in the chosen country
AVG_SPEED=0 # Variable for storing the average speed of each server

for i in {1.."${NUM_SERVERS}"}; do
  # Get the name of the server associated with the random number
  RANDOM_SERVER=$(random_server "${SERVER_ARRAY}")
  
  # Reset AVG_SPEED for the next server
  AVG_SPEED=0
  
  # Compute average of
  test_speed "${RANDOM_SERVER}" "${NUM_TESTS}"
  
  # If the avg speed is the fastest of the servers so far, then update the
  # max speed and the fastest server variables
  if [ $(("${AVG_SPEED}" > "${MAX_SPEED}")) ]; then
    MAX_SPEED="${AVG_SPEED}"
    BEST_SERVER="${RANDOM_SERVER}"
    echo "Max Speed: ${MAX_SPEED}"
  fi
done

# Connect to the fastest server
openvpn "${BEST_SERVER}"
